circleci-matrix: Pass CIRCLECI env var
This commit fixes the following error:

LookupError: unknown service: None of the environment variables TRAVIS, CIRCLECI, APPVEYOR are set to 'true' or 'True'