Require newer setuptools to fix building of Python 3.4 wheels
This commit re-applies a fix similar to 72f9243 (ci: Fix python 3.4 windows
build updating version of setuptools) that was inadvertently reverted
in b7ec14c (ci: minor tweaks).

It fixes the following error:

```
Traceback (most recent call last):
  File "setup.py", line 78, in <module>
    setup_requires=setup_requires
  File "C:\Python34-x64\lib\site-packages\skbuild\setuptools_wrap.py", line 512, in setup
    cmkr = cmaker.CMaker(cmake_executable)
  File "C:\Python34-x64\lib\site-packages\skbuild\cmaker.py", line 93, in __init__
    self.platform = get_platform()
  File "C:\Python34-x64\lib\site-packages\skbuild\platform_specifics\platform_factory.py", line 18, in get_platform
    return windows.WindowsPlatform()
  File "C:\Python34-x64\lib\site-packages\skbuild\platform_specifics\windows.py", line 83, in __init__
    vs_year),
  File "C:\Python34-x64\lib\site-packages\skbuild\platform_specifics\windows.py", line 200, in __init__
    vc_env = _get_msvc_compiler_env(VS_YEAR_TO_VERSION[year])
  File "C:\Python34-x64\lib\site-packages\skbuild\platform_specifics\windows.py", line 138, in _get_msvc_compiler_env
    from setuptools import monkey
ImportError: cannot import name 'monkey'
```