circleci: Fix build using manylinux2010 image
This commit updates to version manylinux2010 based on Centos6, a more recent version
of Centos. See https://www.python.org/dev/peps/pep-0571/

It should address the following error:

  /work/src/Utilities/cmlibuv/src/unix/linux-core.c: In function ‘uv__platform_loop_init’:
  /work/src/Utilities/cmlibuv/src/unix/linux-core.c:88:22: error: ‘EPOLL_CLOEXEC’ undeclared (first use in this function)
     fd = epoll_create1(EPOLL_CLOEXEC);
                        ^