Update build-system to support building wheel using manylinux1
As discussed in [1], starting with CMake 3.14.0, version of libuv
bundled in CMake doesn't support being built with manylinux1.

This commit explicitly downloads an older version of libuv that can
be built on system with older kernel.

To avoid link error like the following, -lrt linker flag is specified:

  /work/libuv-install/lib64/libuv_a.a(linux-core.c.o): In function `uv__hrtime':
  linux-core.c:(.text+0xb58): undefined reference to `clock_getres'
  linux-core.c:(.text+0xbab): undefined reference to `clock_gettime'
  /work/libuv-install/lib64/libuv_a.a(linux-core.c.o): In function `uv_uptime':
  linux-core.c:(.text+0xd91): undefined reference to `clock_gettime'
  linux-core.c:(.text+0xda7): undefined reference to `clock_gettime'
  collect2: error: ld returned 1 exit status


See #78

[1] https://gitlab.kitware.com/cmake/cmake/issues/19311