tests: Fix test_wheel on MacOSX resolving all symbolic links
This commit fixes the following error:

        output = virtualenv.run("cmake -P %s" % str(test_script), capture=True)
>       assert output.startswith(virtualenv.virtualenv.replace(os.sep, "/"))
E       assert False
E        +  where False = <built-in method startswith of str object at 0x1085b11b0>('/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/tmpms0j9nu3/.env')
E        +    where <built-in method startswith of str object at 0x1085b11b0> = '/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/tmpms0j9nu3/.env/lib/python3.4/site-packages/cmake/data/CMake.app/Contents/bin/cmake\n'.startswith
E        +    and   '/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/tmpms0j9nu3/.env' = <built-in method replace of Path object at 0x1085c1de0>('/', '/')
E        +      where <built-in method replace of Path object at 0x1085c1de0> = Path('/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/tmpms0j9nu3/.env').replace
E        +        where Path('/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/tmpms0j9nu3/.env') = <pytest_virtualenv.VirtualEnv object at 0x108595128>.virtualenv
E        +      and   '/' = os.sep